### ISSUE TITLE
Connect Travis CI to project

### ISSUE THREAD

**Issue by DrewRomanyk** [DrewRomanyk/glamrous.me#11]

**Comment by ThomasGaubert** [comment]
Connected, needs to be able to run tests.

Of note is that the gcloud cli requires Python 2.7 while our project wants 3.x. We'll need to figure out how to rectify this for Travis.

**Comment by rperce** [comment]
I assume both can run docker just fine? I'm working on cleaning up the distinction between server-running and development-build-tool-running docker images; once we know what we want to do for tests we can just plop it in a docker image and have travis run that directly, yeah?

**Comment by ThomasGaubert** [comment]
Oh yeah, I don't see why that wouldn't work. 👍
