### ISSUE TITLE
update technical report

### ISSUE THREAD

**Issue by DrewRomanyk** [DrewRomanyk/glamrous.me#19]
- [x] 3750 words
- [x] use cases, RESTful API, models, tools, hosting, and DB
- [x] good sections, multiple pages, good headers, figures, and grammar
- [x] table of contents ( #36 )

**Comment by rperce** [comment]
- [x] ~technical details on filtering and pagination~ actually no
- [x] Dockerfile.db is a thing now, make sure to add to Docker section
- [x] React architecture
