### ISSUE TITLE
Add table of contents to report

### ISSUE THREAD

**Issue by ThomasGaubert** [DrewRomanyk/glamrous.me#36]

**Comment by rperce** [comment]
I looking into some utilities that purportedly do this ([marked-toc](https://www.npmjs.com/package/marked-toc) and [markdown-toc](https://github.com/jonschlinkert/markdown-toc)) but both want to run in node.js, not the browser, so it looks like we'll have to roll our own. I've got an idea of how to handle it, though; I expect it to be well feasible.

**Comment by DrewRomanyk** [comment]
Handled by: 20027788c5e77d0e615c948dd9ec64bdbb84f45d
