### ISSUE TITLE
Critiques

### ISSUE THREAD

**Issue by DrewRomanyk** [DrewRomanyk/glamrous.me#57]
- [ ] Our site
- [ ] Space cowboys critique

**Comment by DrewRomanyk** [comment]
Glamrous.me

What did we do well?
- Devops: automating testing, Dockerizing our code
- Planning and separating work of who does what.
- Defined our own front-end design language that wasn't too bootstrappy

What did we learn?
- Docker & using Docker-compose to virtualize the whole environment to make it easy to work on one computer or the next

What can we do better?
- More data sources
- More love given to Front-end design
- Optimize back-end code
- Refactor front-end code

What puzzles us?
- CSS

Space cowboys:

What did they do well?
- Able to combine 6 APIs into one seamless data source.

What did we learn from their website?
- Space is awesome!

What can they do better?
- Not mobile friendly
- Graphics take too long to load, shows the picture loading from the top to bottom.
- Fix filtering, and also work on filtering for galaxies and satellites as it said to compare it to Jupiter.
- Less Bootstrap Design please
- No easy way to get to the end of pagination or tell how many pages it is

What puzzles us about their website?
- Background for pages that aren't the front page is distracting and a curious front-end choice.

**Comment by myopark** [comment]
Glamrous.me
What did we do well?

-Smooth transition from page to page.
-Front end material design
-Assigning issues and keeping track of our TODOS

What did we learn?
-Learning more about the tools and frameworks like React and Docker. 
What can we do better?
-Better Design
- More specific sorting and brands

What puzzles us?
- Centering images was extremely difficult for some reason

Space cowboys:

What did they do well?
-I like their topic
-how they filtered their content

What did we learn from their website?
-Space
-Flashy gif backgrounds are back in style

What can they do better?
-no flashy gif background. Myspace memories.
-images are loading slowly
-images aren't proportionate so some are stretched out.
-Loading stars when choose a filter. Takes too long or nothing is there? No response for the user for that.

What's puzzling about their website? 
-where they got their data.

**Comment by Cpiely** [comment]
Glamrous:
Good:
- Scales great with different devices and window sizes
- Is very glamarous
Could be better:
- The category and tag pages feel like they could have a little more
Space Cowboys:
Good:
- I like that the tab title changes to each page
- The zooming on the images of the stars and galaxies
Could be better:
- Filtering seems a little off
- Background images could be better

**Comment by ThomasGaubert** [comment]
## Glamrous

### What did we do well?
* Fantastic development/testing/production environment using Docker
* Continuous deployment to our own infrastructure (Cloud Compute)
* Filtering/pagination is slick
* Distribution of tasks

### What did we learn?
* Docker container networking
* Honestly most of the Docker stuff

### What can we do better?
* Having all team members contribute
* Faster load times (especially on the products page)

### What puzzles us?
* CSS, especially with the carousel
* Literally just CSS 🙃 

## SpaceCowboys

### What did they do well?
* Loads quickly
* Galaxy image viewer is awesome

### What did we learn from their website?
* More about space and what's in it?

### What can they do better?
* [Not a huge fan](https://xkcd.com/1378/) of the animated background
* Odd choice of using a dropdown for the sorting
* Add more filtering options? Can only compare to Jupiter... (at least as of writing this)
* Add text to main page

### What's puzzling about their website?
* No text on main page (what does this site do? / what is it for?)
* Nitpick: images of galaxies/planets/etc. end up looking the same which is unfortunate

**Comment by thomas-potnuru** [comment]
Glamrous.me
What did we do well?

Website looks nice.
Website is fast and responsive
Everything on the front end loads after all the information is there
Visualization is amazing

What did we learn?
How to github and docker
How to design APIs

What can we do better?
More API sources

What puzzles us?
Unit testing front-end

Space cowboys:

What did they do well?
Neat design
Beautiful front cover pictures
Good filtering options for each object

What did we learn from their website?
Loading pictures on demand vs. buffering them and then loading

What can they do better?
Images pop in instead of them all showing up

What's puzzling about their website?
Front page to minimalistic
