### ISSUE TITLE
Has at least 5 commits

### ISSUE THREAD

**Issue by DrewRomanyk** [DrewRomanyk/glamrous.me#8]
- [x] fd6cb3de72e400e357834b7094feab1bf5bc3d12
- [x] 1d44489da1876bac1fae4a448109fce79e3b831c
- [x] 5204258a1d41435f89e62a3a1611191f7c6bd437
- [x] dacc970aee9068f6791f272d37d959f248d6415a
- [x] 1cde78b09002eeb3284e55e27aa3da87755a771f

**Comment by rperce** [comment]
@DrewRomanyk committed number 5, 1cde78b, so I'm assigning this one to him.
